import Head from "next/head";
import Navigation from "../Navigation";
import styles from "@/styles/DefaulLayout.module.scss";
import Footer from "../Footer";

export default function DefaulLayout({ children }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>RFS La Huasteca Nuevo Leon</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <main className={styles.main}>{children}</main>
      <Footer />
    </>
  );
}
